<?php
echo "
<nav>
    <div>
        <ul>
            <li><a href='index.php'><strong>People Health Pharmacy</strong></a></li>
            <li><a href='productform.php'>Add Product</a></li>
            <li><a href='editproductform.php'>Edit Product</a></li>
            <li><a href='salesform.php'>Add Sale</a></li>
            <li><a href='editsalesform.php'>Edit Sale</a></li>
            <li><a href='view.php'>View</a></li>
            <li>Query</li>
        </ul>
        <ul>
            <li>Log Out</li>
        </ul>
    </div>
</nav>";
?>